spring:
  datasource:
    url: jdbc:h2:mem:priceProviderService
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    show-sql: true          # Enable SQL logging
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
price-provider-service:
  initialize:
    data-folder: "src/main/resources/initialize/"
    sample-data-on: true
    entity:
      price-row:
        import-groups: EUR,USD,EUR.customer-a
logging:
  pattern:
  level:
    org.hibernate.orm.jdbc.bind: trace